image: hashicorp/packer:light

stages:
  - build

build_job:
  stage: build
  script:
    - echo "Running CI job..."
  tags:
    - docker

build_debian:
  stage: build
  script:
    - cd ci/amd64/debian
    - packer init .
    - packer build build.amd64-debian.pkr.hcl