contact_links:
  - name: Have an idea for a new app in the RaspiBlitz? Make a suggestion in the app ideas section
    url: https://github.com/raspiblitz/raspiblitz/discussions/categories/feature-app-ideas
    about: Feature and app ideas
