name: arm64-rpi-lean-image-build

on:
  push:
    branches: [ "dev", "v1.8", "v1.9" ]
    paths:
      - 'build_sdcard.sh'
      - 'home.admin/bitcoin.install.sh'
      - 'home.admin/lnd.install.sh'
      - 'home.admin/cl.install.sh'
      - 'home.admin/cl-plugin.cln-grpc.sh'
      - 'home.admin/tor.install.sh'
      - 'home.admin/blitz.i2pd.sh'
      - 'home.admin/blitz.web.sh'
      - 'home.admin/bonus.nodejs.sh'
      - 'home.admin/bonus.rtl.sh'
      - 'home.admin/bonus.btcpayserver.sh'
      - 'home.admin/bonus.thunderhub.sh'
      - 'home.admin/bonus.jam.sh install'
      - 'home.admin/bonus.mempool.sh'
      - 'home.admin/blitz.web.api.sh'
      - 'home.admin/blitz.web.ui.sh'
      - 'home.admin/blitz.display.sh'
      - 'ci/arm64-rpi/**'
  pull_request:
    branches: [ "dev", "v1.8", "v1.9" ]
    paths:
      - 'build_sdcard.sh'
      - 'home.admin/bitcoin.install.sh'
      - 'home.admin/lnd.install.sh'
      - 'home.admin/cl.install.sh'
      - 'home.admin/cl-plugin.cln-grpc.sh'
      - 'home.admin/tor.install.sh'
      - 'home.admin/blitz.i2pd.sh'
      - 'home.admin/blitz.web.sh'
      - 'home.admin/bonus.nodejs.sh'
      - 'home.admin/bonus.rtl.sh'
      - 'home.admin/bonus.btcpayserver.sh'
      - 'home.admin/bonus.thunderhub.sh'
      - 'home.admin/bonus.jam.sh install'
      - 'home.admin/bonus.mempool.sh'
      - 'home.admin/blitz.web.api.sh'
      - 'home.admin/blitz.web.ui.sh'
      - 'home.admin/blitz.display.sh'
      - 'ci/arm64-rpi/**'
  workflow_dispatch:

jobs:
  arm64-rpi-image-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Hello Raspiblitz
        run: echo "Building the raspiblitz-arm64-rpi-lean-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}"

      - name: Run the build script
        run: |
          cd ci/arm64-rpi
          bash packer.build.arm64-rpi.sh lean $GITHUB_ACTOR $GITHUB_HEAD_REF

      - name: Compute checksum of the raw image
        run: |
          cd ci/arm64-rpi
          sha256sum raspiblitz-arm64-rpi-lean.img > raspiblitz-arm64-rpi-lean.img.sha256

      - name: Compress image
        run: |
          cd ci/arm64-rpi
          gzip -v9 raspiblitz-arm64-rpi-lean.img

      - name: Compute checksum of the compressed image
        run: |
          cd ci/arm64-rpi
          sha256sum raspiblitz-arm64-rpi-lean.img.gz > raspiblitz-arm64-rpi-lean.img.gz.sha256

      - name: Upload the image and checksums
        uses: actions/upload-artifact@v3
        with:
          name: raspiblitz-arm64-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: |
            ${{ github.workspace }}/ci/arm64-rpi/raspiblitz-arm64-rpi-lean.img.sha256
            ${{ github.workspace }}/ci/arm64-rpi/raspiblitz-arm64-rpi-lean.img.gz
            ${{ github.workspace }}/ci/arm64-rpi/raspiblitz-arm64-rpi-lean.img.gz.sha256
