#!/bin/bash

# https://github.com/BoltzExchange/boltz-client/releases
BOLTZCLI_VERSION="v2.12.0"

APPID="boltzcli"
APPUSER="boltz"
BOLTZCLI_CMD="boltzcli --datadir /mnt/hdd/app-data/boltzcli"

# GPG verification
PGPfingerprint="8918FFBFFB49E93EF256D930542A7F22A3BD9CB0"
PGPpubkeyLink="https://boltz.exchange/static/boltz.asc"

# command info
if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "-help" ]; then
  echo "# Config script for Boltz Client ${BOLTZCLI_VERSION}"
  echo "# Supports CLN and LND"
  echo "# bonus.boltzcli.sh [on|off|menu|update]"
  echo "# bonus.boltzcli.sh [status|prestart]"
  echo "# bonus.boltzcli.sh install"
  exit 1
fi

echo "# Running: 'bonus.${APPID}.sh $*'"

source /mnt/hdd/app-data/raspiblitz.conf 2>/dev/null
source /home/admin/raspiblitz.info 2>/dev/null

# source existing aliases for CLN and LND (if available)
source /home/admin/_aliases 2>/dev/null || true

# fallback: define aliases inline if not sourced
if [ -z "${lightningcli_alias}" ]; then
  lightningcli_alias="sudo -u bitcoin /usr/local/bin/lightning-cli --conf=/home/bitcoin/.lightning/config"
fi
if [ -z "${lncli_alias}" ]; then
  # LND uses mainnet port 10009, testnet 11009, signet 13009
  if [ "${chain}" = "test" ]; then
    lncli_alias="sudo -u bitcoin /usr/local/bin/lncli -n=testnet --rpcserver=localhost:11009"
  elif [ "${chain}" = "sig" ]; then
    lncli_alias="sudo -u bitcoin /usr/local/bin/lncli -n=signet --rpcserver=localhost:13009"
  else
    lncli_alias="sudo -u bitcoin /usr/local/bin/lncli -n=mainnet --rpcserver=localhost:10009"
  fi
fi

# Helper: detect which lightning node boltz is configured for
detectBoltzNode() {
  if [ "${lightning}" = "cl" ]; then
    echo "cln"
  elif [ "${lightning}" = "lnd" ]; then
    echo "lnd"
  elif [ "${cl}" = "on" ] && [ "${lnd}" = "on" ]; then
    if [ "${lightning}" = "cl" ]; then
      echo "cln"
    else
      echo "lnd"
    fi
  elif [ "${cl}" = "on" ]; then
    echo "cln"
  elif [ "${lnd}" = "on" ]; then
    echo "lnd"
  else
    echo "none"
  fi
}

# Helper: get on-chain wallet balance (unreserved)
getWalletBalance() {
  local node_type=$(detectBoltzNode)
  if [ "${node_type}" = "cln" ]; then
    ${lightningcli_alias} listfunds 2>/dev/null | jq -r '[.outputs[] | select(.reserved == false and .status == "confirmed") | .amount_msat | tonumber] | add / 1000 | floor'
  elif [ "${node_type}" = "lnd" ]; then
    # LND: sum confirmed balance (sats)
    ${lncli_alias} walletbalance 2>/dev/null | jq -r '.confirmed_balance | tonumber'
  else
    echo "0"
  fi
}

# Helper: generate new on-chain address
getNewAddress() {
  local node_type=$(detectBoltzNode)
  if [ "${node_type}" = "cln" ]; then
    ${lightningcli_alias} newaddr 2>/dev/null | jq -r '.p2tr // .bech32 // empty'
  elif [ "${node_type}" = "lnd" ]; then
    # LND: generate taproot address (p2tr)
    ${lncli_alias} newaddress p2tr 2>/dev/null | jq -r '.address // empty'
  else
    echo ""
  fi
}

# determine data directory
BOLTZ_DATA_DIR="/mnt/hdd/app-data/${APPID}"
BOLTZ_CONF="${BOLTZ_DATA_DIR}/boltz.toml"
BOLTZ_BACKUP_FILE="${BOLTZ_DATA_DIR}/swap_mnemonic.backup"

#########################
# HELPER: detect architecture
#########################
detectArch() {
  isAARCH64=$(uname -m | grep -c 'aarch64')
  isX86_64=$(uname -m | grep -c 'x86_64')
  if [ ${isAARCH64} -eq 1 ]; then
    ARCH="arm64"
  elif [ ${isX86_64} -eq 1 ]; then
    ARCH="amd64"
  else
    echo "# FAIL: unsupported architecture $(uname -m)"
    exit 1
  fi
}

#########################
# HELPER: generate boltz.toml
#########################
generateConfig() {
  # determine network
  if [ "${chain}" = "test" ]; then
    BOLTZ_NETWORK="testnet"
  elif [ "${chain}" = "sig" ]; then
    BOLTZ_NETWORK="regtest"
  else
    BOLTZ_NETWORK="mainnet"
  fi

  # determine node type
  BOLTZ_NODE=""
  if [ "${lightning}" = "cl" ]; then
    BOLTZ_NODE="cln"
  elif [ "${lightning}" = "lnd" ]; then
    BOLTZ_NODE="lnd"
  elif [ "${cl}" = "on" ] && [ "${lnd}" = "on" ]; then
    # both active - prefer the default
    if [ "${lightning}" = "cl" ]; then
      BOLTZ_NODE="cln"
    else
      BOLTZ_NODE="lnd"
    fi
  elif [ "${cl}" = "on" ]; then
    BOLTZ_NODE="cln"
  elif [ "${lnd}" = "on" ]; then
    BOLTZ_NODE="lnd"
  fi

  cat > "${BOLTZ_CONF}" <<EOF
# Boltz Client configuration - generated by RaspiBlitz
# https://client.docs.boltz.exchange/configuration.html

network = "${BOLTZ_NETWORK}"
node = "${BOLTZ_NODE}"
pro = true
referralId = "raspiblitz"
loglevel = "info"

[LIGHTNING]
routingFeeLimitPpm = 2500

[CLN]
host = "127.0.0.1"
port = 4772
datadir = "/home/bitcoin/.lightning"

[LND]
host = "127.0.0.1"
port = 10009
datadir = "/mnt/hdd/app-data/lnd"

[RPC]
host = "127.0.0.1"
port = 9002
restHost = "127.0.0.1"
restPort = 9003
noMacaroons = false

[DATABASE]
path = "${BOLTZ_DATA_DIR}/boltz.db"
EOF

  chmod 640 "${BOLTZ_CONF}"
  chown ${APPUSER}:${APPUSER} "${BOLTZ_CONF}"
}

#########################
# INFO
#########################

isInstalled=$(sudo ls /etc/systemd/system/${APPID}.service 2>/dev/null | grep -c "${APPID}.service")
isRunning=$(systemctl status ${APPID} 2>/dev/null | grep -c 'active (running)')

#########################
# STATUS
#########################
if [ "$1" = "status" ]; then
  echo "appID='${APPID}'"
  echo "version='${BOLTZCLI_VERSION}'"
  echo "isInstalled=${isInstalled}"
  echo "isRunning=${isRunning}"
  if [ ${isInstalled} -eq 1 ]; then
    echo "dataDir='${BOLTZ_DATA_DIR}'"
  fi
  exit 0
fi

##########################
# MENU
#########################
if [ "$1" = "menu" ]; then

  # check if installed
  if [ ${isInstalled} -eq 0 ]; then
    whiptail --title " Boltz Client " --msgbox "Boltz Client is not installed." 7 40
    exit 0
  fi

  # main info dialog
  dialogTitle=" Boltz Client ${BOLTZCLI_VERSION} "
  statusInfo=""
  if [ ${isRunning} -eq 1 ]; then
    statusInfo="Service: RUNNING"
  else
    statusInfo="Service: NOT RUNNING"
  fi

  # get node type from boltzcli
  nodeType=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} getinfo 2>/dev/null | jq -r '.node // "unknown"')

  dialogText="${statusInfo}\nConnected to: ${nodeType}\nPro rates: enabled\n\nUse the OPTIONS below for swap operations."

  whiptail --title "${dialogTitle}" --yes-button "OK" --no-button "OPTIONS" --yesno "${dialogText}" 12 55
  result=$?

  if [ ${result} -eq 0 ]; then
    exit 0
  fi

  # enforce mnemonic backup if not yet saved (file must exist and be non-empty)
  if [ ! -s "${BOLTZ_BACKUP_FILE}" ]; then
    whiptail --title " Boltz Client - Backup Required " --msgbox \
      "No swap mnemonic backup found.\n\nYou MUST back up your swap mnemonic before using Boltz.\nIt is needed to recover funds locked in swaps if the database is lost.\n\nThe mnemonic will be shown and saved next." 13 65
    MNEMONIC_WORDS=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} swapmnemonic get 2>&1)
    if [ -n "${MNEMONIC_WORDS}" ] && ! echo "${MNEMONIC_WORDS}" | grep -qi "error\|fail"; then
      echo "${MNEMONIC_WORDS}" | sudo tee "${BOLTZ_BACKUP_FILE}" > /dev/null
      sudo chown ${APPUSER}:${APPUSER} "${BOLTZ_BACKUP_FILE}"
      sudo chmod 600 "${BOLTZ_BACKUP_FILE}"
      whiptail --title " Boltz Client - Swap Mnemonic " --msgbox \
        "WRITE DOWN THIS MNEMONIC:\n\n${MNEMONIC_WORDS}\n\nBackup saved to:\n${BOLTZ_BACKUP_FILE} (mode 600)" 16 70
    else
      whiptail --title " Boltz Client " --msgbox "WARNING: Could not retrieve swap mnemonic.\nPlease check that the service is running." 9 55
    fi
  fi

  # options menu loop
  while true; do

    OPTIONS=()
    OPTIONS+=(INFO "Show Boltz Client info (getinfo)")
    OPTIONS+=(PAIRS "Show current swap pairs & fees")
    OPTIONS+=(CREATESWAP "Create Chain -> Lightning swap")
    OPTIONS+=(REVERSESWAP "Create Lightning -> Chain swap")
    OPTIONS+=(LISTSWAPS "List recent swaps")
    # add sweep option only if CLN is available
    if [ "${cl}" = "on" ] || [ "${lightning}" = "cl" ]; then
      OPTIONS+=(SWEEP "Sweep CLN UTXO to Lightning (Boltz)")
    fi
    OPTIONS+=(MNEMONIC "Show swap mnemonic (BACKUP!)")
    OPTIONS+=(LOG "Show service logs")

    WIDTH=66
    CHOICE_HEIGHT=$(("${#OPTIONS[@]}/2+1"))
    HEIGHT=$((CHOICE_HEIGHT+7))
    CHOICE=$(dialog --clear \
                  --title " Boltz Client - Options" \
                  --ok-label "Select" \
                  --cancel-label "Back" \
                  --menu "Choose one of the following options:" \
                  $HEIGHT $WIDTH $CHOICE_HEIGHT \
                  "${OPTIONS[@]}" \
                  2>&1 >/dev/tty)

    # break on cancel/back
    if [ $? -ne 0 ] || [ -z "${CHOICE}" ]; then
      break
    fi

    case $CHOICE in
      INFO)
        clear
        echo "# Boltz Client - getinfo"
        echo
        sudo -u ${APPUSER} ${BOLTZCLI_CMD} getinfo 2>&1
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      PAIRS)
        clear
        echo "# Boltz Client - Current Swap Pairs & Fees"
        echo
        sudo -u ${APPUSER} ${BOLTZCLI_CMD} getpairs 2>&1
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      CREATESWAP)
        # === Step 1/3: Amount input ===
        amountSat=$(whiptail --title " Boltz Submarine [1/3] - Amount " \
          --inputbox "Enter amount in sats to swap Chain -> Lightning:" 9 55 "1000000" \
          3>&1 1>&2 2>&3)
        exitStatus=$?
        if [ ${exitStatus} -ne 0 ] || [ -z "${amountSat}" ]; then
          continue
        fi

        # === Step 2/3: Source selection ===
        # get wallet balance (works with both CLN and LND)
        NODE_TYPE=$(detectBoltzNode)
        WALLET_LABEL="${NODE_TYPE} internal wallet"
        WALLET_BALANCE=$(getWalletBalance)
        if [ -z "${WALLET_BALANCE}" ] || [ "${WALLET_BALANCE}" = "0" ] || [ "${WALLET_BALANCE}" = "null" ]; then
          WALLET_BALANCE=0
        fi

        SRC_CHOICE=$(whiptail --title " Boltz Submarine [2/3] - Source " \
          --radiolist "Select source of on-chain BTC:\n\nUse SPACE to select, ENTER to confirm:" \
          11 65 2 \
          "DEFAULT" "${WALLET_LABEL} (${WALLET_BALANCE} sats available)" ON \
          "EXTERNAL" "External wallet (I will pay manually)" OFF \
          3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
          continue
        fi

        if [ "${SRC_CHOICE}" = "EXTERNAL" ]; then
          # generate a refund address for safety
          REFUND_ADDR=$(getNewAddress)
          if [ -z "${REFUND_ADDR}" ]; then
            whiptail --title " Boltz Submarine " --msgbox "Could not generate refund address." 9 55
            continue
          fi
          # get swap first to know the deposit address
          clear
          echo "# Creating swap to get deposit address ..."
          SWAP_INFO=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} createswap --json --external-pay --refund "${REFUND_ADDR}" btc ${amountSat} 2>&1)
          if [ $? -ne 0 ]; then
            whiptail --title " Boltz Submarine " --msgbox "Swap creation failed:\n${SWAP_INFO}" 12 70
            continue
          fi
          SWAP_ID=$(echo "${SWAP_INFO}" | jq -r '.id // empty')
          DEPOSIT_ADDR=$(echo "${SWAP_INFO}" | jq -r '.address // empty')

          # show address and QR code
          clear
          echo "# Boltz Submarine Swap - External Payment"
          echo
          echo "Swap ID: ${SWAP_ID}"
          echo
          echo "Deposit Address: ${DEPOSIT_ADDR}"
          echo "Refund Address:  ${REFUND_ADDR} (in case swap fails)"
          echo
          echo "Send EXACTLY ${amountSat} sats to this address."
          echo
          echo "QR Code:"
          echo
          # convert sats to BTC for BIP21 format (1 BTC = 100000000 sats)
          AMOUNT_BTC=$(echo "${amountSat}" | jq -r '. / 100000000 | tostring | if startswith(".") then "0" + . else . end')
          qrencode -t ANSIUTF8 "bitcoin:${DEPOSIT_ADDR}?amount=${AMOUNT_BTC}"
          echo
          echo "Press ENTER to continue"
          read -r
          continue
        fi

        # === Step 3/3: Summary and confirmation (CLN path) ===
        # get pair info for fee calculation
        PAIRS=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} getpairs --json 2>/dev/null)
        FEE_PERCENT=$(echo "${PAIRS}" | jq -r '.submarine[] | select(.pair.from == "BTC" and .pair.to == "BTC") | .fees.percentage // 0')
        FEE_MINER=$(echo "${PAIRS}" | jq -r '.submarine[] | select(.pair.from == "BTC" and .pair.to == "BTC") | .fees.minerFees.BTC // 0')

        # calculate estimated fees
        FEE_SWAP=$(echo "${amountSat} ${FEE_PERCENT}" | jq -r '.[0] * .[1] / 100 | floor')
        TOTAL_FEE=$((FEE_SWAP + FEE_MINER))
        RECEIVE_AMOUNT=$((amountSat - TOTAL_FEE))

        SUMMARY="REVIEW SUBMARINE SWAP DETAILS:\n\n"
        SUMMARY+="Direction:    On-Chain -> Lightning\n"
        SUMMARY+="Send amount:  ${amountSat} sats\n"
        SUMMARY+="Source:       ${WALLET_LABEL}\n"
        SUMMARY+="Boltz fee:    ~${FEE_SWAP} sats (${FEE_PERCENT}%)\n"
        SUMMARY+="Miner fee:    ~${FEE_MINER} sats\n"
        SUMMARY+="Receive:      ~${RECEIVE_AMOUNT} sats\n\n"
        SUMMARY+=">>> Press YES to CREATE the swap <<<\n>>> Press NO to CANCEL <<<"

        whiptail --title " Boltz Submarine [3/3] - Confirm " \
          --yesno "${SUMMARY}" 18 70 \
          --yes-button "CREATE" --no-button "CANCEL"
        if [ $? -ne 0 ]; then
          continue
        fi

        # Create the swap
        clear
        echo "# Creating submarine swap for ${amountSat} sats ..."
        echo
        sudo -u ${APPUSER} ${BOLTZCLI_CMD} createswap btc ${amountSat} 2>&1
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      REVERSESWAP)
        # === Step 1/3: Amount input ===
        amountSat=$(whiptail --title " Boltz Reverse [1/3] - Amount " \
          --inputbox "Enter amount in sats to swap Lightning -> Chain:" 9 55 "100000" \
          3>&1 1>&2 2>&3)
        exitStatus=$?
        if [ ${exitStatus} -ne 0 ] || [ -z "${amountSat}" ]; then
          continue
        fi

        # === Step 2/3: Destination address selection ===
        NODE_TYPE=$(detectBoltzNode)
        WALLET_LABEL="${NODE_TYPE} internal wallet"
        ADDR_CHOICE=$(whiptail --title " Boltz Reverse [2/3] - Destination " \
          --radiolist "Select where to receive the on-chain BTC:\n\nUse SPACE to select, ENTER to confirm:" \
          11 60 2 \
          "DEFAULT" "${WALLET_LABEL} (new address)" ON \
          "CUSTOM" "Specify custom on-chain address" OFF \
          3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
          continue
        fi

        if [ "${ADDR_CHOICE}" = "CUSTOM" ]; then
          DEST_ADDR=$(whiptail --title " Boltz Reverse [2/3] - Destination " \
            --inputbox "Enter on-chain BTC address:" 9 55 "" \
            3>&1 1>&2 2>&3)
          if [ $? -ne 0 ] || [ -z "${DEST_ADDR}" ]; then
            continue
          fi
        else
          # get new address from wallet (CLN or LND)
          DEST_ADDR=$(getNewAddress)
          if [ -z "${DEST_ADDR}" ]; then
            whiptail --title " Boltz Reverse " --msgbox "Could not get address from wallet." 9 55
            continue
          fi
        fi

        # === Step 3/3: Summary and confirmation ===
        # get pair info for fee calculation (reverse = Lightning -> Chain)
        PAIRS=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} getpairs --json 2>/dev/null)
        FEE_PERCENT=$(echo "${PAIRS}" | jq -r '.reverse[] | select(.pair.from == "BTC" and .pair.to == "BTC") | .fees.percentage // 0')
        FEE_MINER=$(echo "${PAIRS}" | jq -r '.reverse[] | select(.pair.from == "BTC" and .pair.to == "BTC") | .fees.minerFees // 0')

        # calculate estimated fees
        FEE_SWAP=$(echo "${amountSat} ${FEE_PERCENT}" | jq -r '.[0] * .[1] / 100 | floor')
        TOTAL_FEE=$((FEE_SWAP + FEE_MINER))
        RECEIVE_AMOUNT=$((amountSat - TOTAL_FEE))

        SUMMARY="REVIEW REVERSE SWAP DETAILS:\n\n"
        SUMMARY+="Direction:    Lightning -> On-Chain\n"
        SUMMARY+="Send amount:  ${amountSat} sats\n"
        SUMMARY+="Boltz fee:    ~${FEE_SWAP} sats (${FEE_PERCENT}%)\n"
        SUMMARY+="Miner fee:    ~${FEE_MINER} sats\n"
        SUMMARY+="Receive:      ~${RECEIVE_AMOUNT} sats\n\n"
        SUMMARY+="Destination:  ${DEST_ADDR}\n\n"
        SUMMARY+">>> Press YES to CREATE the swap <<<\n"
        SUMMARY+">>> Press NO to CANCEL <<"

        whiptail --title " Boltz Reverse [3/3] - Confirm " \
          --yesno "${SUMMARY}" 18 70 \
          --yes-button "CREATE" --no-button "CANCEL"
        if [ $? -ne 0 ]; then
          continue
        fi

        # Create the swap
        clear
        echo "# Creating reverse swap for ${amountSat} sats ..."
        echo "# Destination: ${DEST_ADDR}"
        echo
        sudo -u ${APPUSER} ${BOLTZCLI_CMD} createreverseswap btc ${amountSat} ${DEST_ADDR} 2>&1
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      LISTSWAPS)
        clear
        echo "# Boltz Client - Recent Swaps"
        echo
        sudo -u ${APPUSER} ${BOLTZCLI_CMD} listswaps 2>&1
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      SWEEP)
        /home/admin/config.scripts/cl.boltz-sweep.sh
        ;;
      MNEMONIC)
        clear
        echo "# ================================================"
        echo "# IMPORTANT: Back up this swap mnemonic securely!"
        echo "# It can recover funds locked in swaps if the"
        echo "# database is lost."
        echo "# ================================================"
        echo
        MNEMONIC_WORDS=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} swapmnemonic get 2>&1)
        echo "${MNEMONIC_WORDS}"
        echo
        # save/update backup file
        if [ -n "${MNEMONIC_WORDS}" ] && ! echo "${MNEMONIC_WORDS}" | grep -qi "error\|fail"; then
          echo "${MNEMONIC_WORDS}" | sudo tee "${BOLTZ_BACKUP_FILE}" > /dev/null
          sudo chown ${APPUSER}:${APPUSER} "${BOLTZ_BACKUP_FILE}"
          sudo chmod 600 "${BOLTZ_BACKUP_FILE}"
          echo "# Backup saved to: ${BOLTZ_BACKUP_FILE} (mode 600)"
        else
          echo "# WARNING: Could not extract mnemonic for backup"
        fi
        echo
        echo "# To reset/generate a new mnemonic (advanced):"
        echo "#   boltzcli swapmnemonic set --generate"
        echo "# After reset, restart to auto-save backup:"
        echo "#   sudo systemctl restart boltzcli"
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
      LOG)
        clear
        echo "# Boltz Client - Recent Logs (last 50 lines)"
        echo
        sudo journalctl -u ${APPID} -n 50 --no-pager
        echo
        echo "Press ENTER to continue"
        read -r
        ;;
    esac

  done

  exit 0
fi

##########################
# INSTALL (binary download)
##########################
if [ "$1" = "install" ]; then

  # check if already installed
  if [ -f /usr/local/bin/boltzd ] && [ -f /usr/local/bin/boltzcli ]; then
    echo "# Boltz Client binaries already installed - skipping"
    exit 0
  fi

  echo "# Installing Boltz Client ${BOLTZCLI_VERSION} ..."

  detectArch
  echo "# Architecture: ${ARCH}"

  downloadDir="/tmp/boltz-install"
  mkdir -p "${downloadDir}"
  cd "${downloadDir}" || exit 1

  # download binary, manifest, and signature
  binaryName="boltz-client-linux-${ARCH}-${BOLTZCLI_VERSION}.tar.gz"
  manifestName="boltz-client-manifest-${BOLTZCLI_VERSION}.txt"
  sigName="${manifestName}.sig"

  echo "# Downloading ${binaryName} ..."
  wget -q -N "https://github.com/BoltzExchange/boltz-client/releases/download/${BOLTZCLI_VERSION}/${binaryName}" || { echo "# FAIL: download binary"; exit 1; }
  wget -q -N "https://github.com/BoltzExchange/boltz-client/releases/download/${BOLTZCLI_VERSION}/${manifestName}" || { echo "# FAIL: download manifest"; exit 1; }
  wget -q -N "https://github.com/BoltzExchange/boltz-client/releases/download/${BOLTZCLI_VERSION}/${sigName}" || { echo "# FAIL: download signature"; exit 1; }

  # import GPG key
  echo "# Importing Boltz GPG key ..."
  curl -sS "${PGPpubkeyLink}" | gpg --import 2>/dev/null

  # verify signature
  echo "# Verifying GPG signature ..."
  gpgResult=$(gpg --verify "${sigName}" "${manifestName}" 2>&1)
  goodSig=$(echo "${gpgResult}" | grep -c 'Good signature')
  correctKey=$(echo "${gpgResult}" | grep -c "${PGPfingerprint}")
  if [ ${goodSig} -lt 1 ] || [ ${correctKey} -lt 1 ]; then
    echo "# FAIL: GPG signature verification failed"
    echo "${gpgResult}"
    exit 1
  fi
  echo "# GPG signature verified OK"

  # verify checksum
  echo "# Verifying SHA256 checksum ..."
  sha256sum --ignore-missing -c "${manifestName}" 2>&1 | grep -q "OK"
  if [ $? -ne 0 ]; then
    echo "# FAIL: SHA256 checksum verification failed"
    exit 1
  fi
  echo "# SHA256 checksum verified OK"

  # extract and install
  echo "# Extracting binaries ..."
  tar -xzf "${binaryName}" || { echo "# FAIL: extract"; exit 1; }

  # find the binaries (may be in bin/, current dir, or a subdirectory)
  BOLTZD_BIN=$(find . -name "boltzd" -type f | head -1)
  BOLTZCLI_BIN=$(find . -name "boltzcli" -type f | head -1)

  if [ -n "${BOLTZD_BIN}" ] && [ -n "${BOLTZCLI_BIN}" ]; then
    sudo install -m 0755 "${BOLTZD_BIN}" /usr/local/bin/boltzd
    sudo install -m 0755 "${BOLTZCLI_BIN}" /usr/local/bin/boltzcli
    echo "# OK - binaries installed to /usr/local/bin/"
  else
    echo "# FAIL: boltzd/boltzcli binaries not found after extraction"
    find . -type f
    exit 1
  fi

  # clean up
  rm -rf "${downloadDir}"
  echo "# Boltz Client ${BOLTZCLI_VERSION} installed"
  exit 0
fi

##########################
# ON
##########################
if [ "$1" = "1" ] || [ "$1" = "on" ]; then

  if [ ${isInstalled} -eq 1 ]; then
    echo "# ${APPID} is already installed."
    exit 0
  fi

  echo "# Installing ${APPID} ..."

  # install binaries if not present
  if [ ! -f /usr/local/bin/boltzd ] || [ ! -f /usr/local/bin/boltzcli ]; then
    /home/admin/config.scripts/bonus.boltzcli.sh install
    if [ $? -ne 0 ]; then
      echo "# FAIL: binary install failed"
      exit 1
    fi
  fi

  # create user
  if ! id "${APPUSER}" &>/dev/null; then
    echo "# Creating user ${APPUSER}"
    sudo adduser --system --group --home /home/${APPUSER} ${APPUSER} || exit 1
  fi

  # add user to relevant groups for lightning node access
  if [ "${cl}" = "on" ] || [ "${lightning}" = "cl" ]; then
    sudo usermod -a -G bitcoin ${APPUSER}
  fi
  if [ "${lnd}" = "on" ] || [ "${lightning}" = "lnd" ]; then
    sudo usermod -a -G lndadmin ${APPUSER}
    # symlink lnd directory for boltzcli access
    sudo rm -rf /home/${APPUSER}/.lnd 2>/dev/null
    sudo ln -s /mnt/hdd/app-data/lnd/ /home/${APPUSER}/.lnd 2>/dev/null
  fi

  # create data directory
  if [ ! -d "${BOLTZ_DATA_DIR}" ]; then
    echo "# Creating data directory ${BOLTZ_DATA_DIR}"
    sudo mkdir -p "${BOLTZ_DATA_DIR}"
  fi
  sudo chown ${APPUSER}:${APPUSER} -R "${BOLTZ_DATA_DIR}"

  # generate config
  echo "# Generating boltz.toml ..."
  sudo -u ${APPUSER} bash -c "$(declare -f generateConfig); \
    chain='${chain}'; lightning='${lightning}'; cl='${cl}'; lnd='${lnd}'; \
    BOLTZ_CONF='${BOLTZ_CONF}'; BOLTZ_DATA_DIR='${BOLTZ_DATA_DIR}'; APPID='${APPUSER}'; \
    generateConfig"

  # create systemd service
  echo "# Creating systemd service: ${APPID}.service"
  cat <<EOF | sudo tee /etc/systemd/system/${APPID}.service >/dev/null
[Unit]
Description=Boltz Client
Wants=bitcoind.service
After=bitcoind.service

[Service]
ExecStartPre=-/home/admin/config.scripts/bonus.boltzcli.sh prestart
ExecStart=/usr/local/bin/boltzd --datadir ${BOLTZ_DATA_DIR}
User=${APPUSER}
Group=${APPUSER}
Type=simple
Restart=always
TimeoutSec=120
RestartSec=30
StandardOutput=journal
StandardError=journal

# Hardening measures
PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable ${APPID}

  # add aliases for convenient CLI usage
  sudo -u admin touch /home/admin/_aliases
  if ! grep -Eq "^alias boltzcli" /home/admin/_aliases; then
    echo "# Adding alias: boltzcli"
    echo "\
alias boltzcli=\"sudo -u ${APPUSER} /usr/local/bin/boltzcli\
 --datadir ${BOLTZ_DATA_DIR}\"
" | sudo tee -a /home/admin/_aliases
  fi
  if ! grep -Eq "^alias boltzlog" /home/admin/_aliases; then
    echo "# Adding alias: boltzlog"
    echo "alias boltzlog=\"sudo journalctl -f -u ${APPID}\"" | sudo tee -a /home/admin/_aliases
  fi
  sudo chown admin:admin /home/admin/_aliases

  # mark as installed in raspiblitz config
  /home/admin/config.scripts/blitz.conf.sh set ${APPID} "on"

  # start service if system is ready
  source <(/home/admin/_cache.sh get state)
  if [ "${state}" == "ready" ]; then
    echo "# Starting ${APPID} service ..."
    sudo systemctl start ${APPID}

    # wait for boltzd to be ready, then save swap mnemonic backup
    echo "# Waiting for boltzd to initialize ..."
    for i in $(seq 1 30); do
      if sudo -u ${APPUSER} ${BOLTZCLI_CMD} getinfo &>/dev/null; then
        MNEMONIC=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} swapmnemonic get 2>/dev/null)
        if [ -n "${MNEMONIC}" ] && ! echo "${MNEMONIC}" | grep -qi "error\|fail"; then
          echo "${MNEMONIC}" | sudo tee "${BOLTZ_BACKUP_FILE}" > /dev/null
          sudo chown ${APPUSER}:${APPUSER} "${BOLTZ_BACKUP_FILE}"
          sudo chmod 600 "${BOLTZ_BACKUP_FILE}"
          echo "# Swap mnemonic saved to ${BOLTZ_BACKUP_FILE} (mode 600)"
        fi
        break
      fi
      sleep 2
    done
  fi

  echo "# OK - Boltz Client installed and enabled"
  echo "# Monitor with: sudo journalctl -f -u ${APPID}"
  exit 0
fi

##########################
# PRESTART
##########################
if [ "$1" = "prestart" ]; then

  echo "## PRESTART CONFIG for ${APPID}"

  # re-read config for current lightning settings
  source /mnt/hdd/app-data/raspiblitz.conf 2>/dev/null

  # regenerate config to pick up any changes
  if [ -d "${BOLTZ_DATA_DIR}" ]; then
    generateConfig
    echo "# Config regenerated at ${BOLTZ_CONF}"
  fi

  # save/update swap mnemonic backup in background (after boltzd is ready)
  (
    for i in $(seq 1 30); do
      sleep 3
      if sudo -u ${APPUSER} ${BOLTZCLI_CMD} getinfo &>/dev/null; then
        MNEMONIC=$(sudo -u ${APPUSER} ${BOLTZCLI_CMD} swapmnemonic get 2>/dev/null)
        if [ -n "${MNEMONIC}" ] && ! echo "${MNEMONIC}" | grep -qi "error\|fail"; then
          echo "${MNEMONIC}" | sudo tee "${BOLTZ_BACKUP_FILE}" > /dev/null
          sudo chown ${APPUSER}:${APPUSER} "${BOLTZ_BACKUP_FILE}"
          sudo chmod 600 "${BOLTZ_BACKUP_FILE}"
        fi
        break
      fi
    done
  ) &

  echo "## PRESTART CONFIG DONE for ${APPID}"
  exit 0
fi

##########################
# OFF / UNINSTALL
##########################
if [ "$1" = "0" ] || [ "$1" = "off" ]; then

  echo "# Removing Boltz Client ..."

  # stop & remove systemd service
  sudo systemctl stop ${APPID} 2>/dev/null
  sudo systemctl disable ${APPID}.service 2>/dev/null
  sudo rm -f /etc/systemd/system/${APPID}.service
  sudo systemctl daemon-reload

  # remove binaries
  sudo rm -f /usr/local/bin/boltzd
  sudo rm -f /usr/local/bin/boltzcli

  # remove aliases
  sudo sed -i '/^alias boltzcli=/d' /home/admin/_aliases
  sudo sed -i '/^alias boltzlog=/d' /home/admin/_aliases

  # delete user
  sudo userdel -rf ${APPUSER} 2>/dev/null

  # mark as uninstalled in raspiblitz config
  /home/admin/config.scripts/blitz.conf.sh set ${APPID} "off"

  # handle data deletion
  if [ "$(echo "$@" | grep -c delete-data)" -gt 0 ]; then
    echo "# Deleting data directory ${BOLTZ_DATA_DIR}"
    sudo rm -rf "${BOLTZ_DATA_DIR}"
  else
    echo "# Keeping data directory ${BOLTZ_DATA_DIR}"
    echo "# To also delete data, run: bonus.boltzcli.sh off delete-data"
  fi

  echo "# OK - Boltz Client removed"
  exit 0
fi

##########################
# UPDATE
##########################
if [ "$1" = "update" ]; then

  echo "# Updating Boltz Client ..."

  # stop service
  sudo systemctl stop ${APPID} 2>/dev/null

  # remove old binaries
  sudo rm -f /usr/local/bin/boltzd
  sudo rm -f /usr/local/bin/boltzcli

  # install new version
  /home/admin/config.scripts/bonus.boltzcli.sh install
  if [ $? -ne 0 ]; then
    echo "# FAIL: update install failed"
    exit 1
  fi

  # restart service
  sudo systemctl start ${APPID}

  echo "# OK - Boltz Client updated to ${BOLTZCLI_VERSION}"
  exit 0
fi

echo "# FAIL - Unknown Parameter $1"
exit 1
